name: Create and Show Tags of ECS By KooCLI By KooCLI
on:
  push:
    branches:
        master
jobs:
  Create-Show-Tags:
    runs-on: ubuntu-latest
    steps:
      - name: Create and Show Tags
        uses: ./
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
          commandList: hcloud ECS NovaListVersions --cli-region="cn-east-3"
