name: Create and Show Tags of ECS By KooCLI By KooCLI
on:
  push:
    branches:
        master-dev
jobs:
  show-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - run: uname -a
#       - run: curl -sSL https://hwcloudcli.obs.cn-north-1.myhuaweicloud.com/cli/latest/hcloud_install.sh -o ./hcloud_install.sh
#       - run: bash ./hcloud_install.sh

#       - run: export STACK=hcloud-toolkit && echo $STACK
#       - run: echo $STACK
      - run: curl -LO "https://hwcloudcli.obs.cn-north-1.myhuaweicloud.com/cli/latest/huaweicloud-cli-linux-amd64.tar.gz"
      - run: tar -zxvf huaweicloud-cli-linux-amd64.tar.gz
      - run: echo $PATH
#       - run: 'export PATH=$PATH:$(pwd)/ && echo $PATH'
      - run: ln -s $(pwd)/hcloud /usr/local/bin/
      - run: echo export STACK=cloudshell >> ~/.bashrc && source ~/.bashrc
      - run: hcloud version
#       - run: export STACK=hcloud-toolkit && echo $STACK && hcloud version
      
      - name: Create and Show Tags
        uses: ./
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
          command_list: |
            hcloud ECS NovaListVersions --cli-region="cn-east-3"
      
#       - run: cat ./hcloud_install.sh -y
