name: Create and Show Tags of ECS By KooCLI By KooCLI
on:
  push:
    branches:
        master-dev
jobs:
  show-version:
    runs-on: ubuntu-latest
    steps:
      - run: curl -sSL https://hwcloudcli.obs.cn-north-1.myhuaweicloud.com/cli/latest/hcloud_install.sh -o ./hcloud_install.sh && bash ./hcloud_install.sh -y
      
      - uses: actions/checkout@v2
      
      - name: Create and Show Tags
        uses: ./
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: cn-north-4
          command_list: |
            hcloud ECS NovaListVersions --cli-region="cn-east-3"
